package com.cs321.gui;

import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

/**
 *
 * @author guero
 */
public class dart extends javax.swing.JFrame {

    /**
     * Total round score.
     */
    private int totalRoundScore = 0;
    /**
     * current throw score.
     */
    private int throwScore = 0;
    /**
     * how many throws happned.
     */
    private int throwRounds = 0;
    /**
     * actual round.
     */
    private int round = 0; //
    /**
     * how many scores were confirmed.
     */
    private int confirmed = 0;
  
  

    /**
     * Creates new form dart
     */
    public dart() {
        initComponents();

        setPanel2Color();

        roundScoreBoxValue.setText("0");

        teamAName.setText("A-34");// sets text for team A's name. 
        teamBName.setText("B-57");//sets text fot team B's name 
        roundValueBox.setText("0");// sets texts for round. 
        throwBoxValue.setText("0/3");//sets texts for Throw number. ex : 1/3
        roundScoreBoxValue.setText("0");//sets text for round score. 
        playingTeamBoxValue.setText("A");//sets text for current playing team. 
        playerNameBoxValue.setText("plr1");//sets text for player's name. 
        throwScoreBoxValue.setText("0");// sets current throw score. 

        
    }

    /**
     * Method to change dartboard surrounding panel's calor randomly at each
     * touch.
     */
    private void setPanel2Color() {
        float hue = (float) Math.random();
        float saturation = 0.9f; // Saturation value between 0.0 and 1.0
        float brightness = 1.0f; // Brightness value between 0.0 and 1.0
        Color randomColor = Color.getHSBColor(hue, saturation, brightness);
        changingLightsBoardPanel.setBackground(randomColor);

    }

    /**
     * C
     * Total round score getter.
     *
     * @return totalRound Score.
     */
    public int getScore() {

        return this.totalRoundScore;
    }

    public int throwScore() {
        return this.throwScore;
    }

    public int throwRounds() {
        return throwRounds;
    }

    /**
     * setter for round.
     *
     * @param round
     */
    public void setRound(int round) {
        this.round = round;

    }

    /**
     * getter for round.
     *
     * @return
     */
    public int getRound() {
        return round;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        playingTeamBox = new javax.swing.JLabel();
        playerNameBox = new javax.swing.JLabel();
        roundScoreBox = new javax.swing.JLabel();
        roundScoreBoxValue = new java.awt.Label();
        requiredScoreBox = new java.awt.Label();
        playingTeamBoxValue = new java.awt.Label();
        playerNameBoxValue = new java.awt.Label();
        label5 = new java.awt.Label();
        teamABox = new java.awt.Label();
        teamBBox = new java.awt.Label();
        teamAName = new java.awt.Label();
        teamBName = new java.awt.Label();
        roundBox = new java.awt.Label();
        roundValueBox = new java.awt.Label();
        throwBox = new java.awt.Label();
        throwBoxValue = new java.awt.Label();
        QuitToMainMenuButton = new java.awt.Button();
        confirmNowButton = new java.awt.Button();
        undoThrowButton = new java.awt.Button();
        throwScoreBox = new javax.swing.JLabel();
        throwScoreBoxValue = new java.awt.Label();
        changingLightsBoardPanel = new javax.swing.JPanel();
        dartBoardPicture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        playingTeamBox.setBackground(new java.awt.Color(204, 0, 51));
        playingTeamBox.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        playingTeamBox.setForeground(new java.awt.Color(204, 0, 51));
        playingTeamBox.setText("Playing Team: ");

        playerNameBox.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        playerNameBox.setForeground(new java.awt.Color(204, 0, 51));
        playerNameBox.setText("Player's name: ");

        roundScoreBox.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        roundScoreBox.setForeground(new java.awt.Color(204, 0, 51));
        roundScoreBox.setText("Round Score: ");

        roundScoreBoxValue.setText("label1");

        requiredScoreBox.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        requiredScoreBox.setText("Required Score 301");

        playingTeamBoxValue.setText("label2");

        playerNameBoxValue.setText("label4");

        label5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label5.setText("__________________________________________________________________________________________________________");

        teamABox.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        teamABox.setText("Team ");

        teamBBox.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        teamBBox.setText("Team ");

        teamAName.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        teamAName.setText("A -34");

        teamBName.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        teamBName.setText("B-57");

        roundBox.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        roundBox.setText("Round");

        roundValueBox.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        roundValueBox.setText("1");

        throwBox.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        throwBox.setText("Throw");

        throwBoxValue.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        throwBoxValue.setText("1/3");

        QuitToMainMenuButton.setBackground(new java.awt.Color(255, 255, 255));
        QuitToMainMenuButton.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        QuitToMainMenuButton.setLabel("Quit to Main Menu");
        QuitToMainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitToMainMenuButtonActionPerformed(evt);
            }
        });

        confirmNowButton.setBackground(new java.awt.Color(255, 255, 255));
        confirmNowButton.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        confirmNowButton.setLabel("Confirm Throw");
        confirmNowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmNowButtonActionPerformed(evt);
            }
        });

        undoThrowButton.setBackground(new java.awt.Color(255, 255, 255));
        undoThrowButton.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        undoThrowButton.setLabel("Undo Throw");
        undoThrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoThrowButtonActionPerformed(evt);
            }
        });

        throwScoreBox.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        throwScoreBox.setForeground(new java.awt.Color(153, 0, 153));
        throwScoreBox.setText("Throw Score: ");

        throwScoreBoxValue.setText("label1");

        dartBoardPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dartBoardPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dartBoard_1.png"))); // NOI18N
        dartBoardPicture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dartBoardPictureMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout changingLightsBoardPanelLayout = new javax.swing.GroupLayout(changingLightsBoardPanel);
        changingLightsBoardPanel.setLayout(changingLightsBoardPanelLayout);
        changingLightsBoardPanelLayout.setHorizontalGroup(
            changingLightsBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changingLightsBoardPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(dartBoardPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        changingLightsBoardPanelLayout.setVerticalGroup(
            changingLightsBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changingLightsBoardPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(dartBoardPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(confirmNowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(requiredScoreBox, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(teamABox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teamAName, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(teamBBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(teamBName, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(259, 259, 259))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(roundBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roundValueBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(throwBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(throwBoxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(232, 232, 232)
                                .addComponent(throwScoreBox)
                                .addGap(19, 19, 19)
                                .addComponent(throwScoreBoxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(QuitToMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(playerNameBox)
                                    .addGap(6, 6, 6))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(playingTeamBox)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(roundScoreBox)
                                .addGap(14, 14, 14)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roundScoreBoxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playingTeamBoxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerNameBoxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changingLightsBoardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(399, Short.MAX_VALUE)
                    .addComponent(undoThrowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(299, 299, 299)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(requiredScoreBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(teamABox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(teamAName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(teamBName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(teamBBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundValueBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(throwBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(throwBoxValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(throwScoreBoxValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(throwScoreBox))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(roundScoreBox)
                            .addComponent(roundScoreBoxValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playingTeamBox)
                            .addComponent(playingTeamBoxValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playerNameBox)
                            .addComponent(playerNameBoxValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(changingLightsBoardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmNowButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuitToMainMenuButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(481, Short.MAX_VALUE)
                    .addComponent(undoThrowButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(67, 67, 67)))
        );

        label5.getAccessibleContext().setAccessibleName("_________________________________________________________________________________________________________________________");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 849, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * This method is responsible for clicking on the dartboard. The method uses
     * Random class to give a score.
     *
     * @param evt
     */
    private void dartBoardPictureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dartBoardPictureMouseClicked
        // TODO add your handling code here:

        if (throwRounds > 2) {
            javax.swing.JOptionPane.showMessageDialog(null, "You completed all 3 Throws ", "Message", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        setPanel2Color();////changes panel's color for fun. 
        Random rand = new Random();
        int score = rand.nextInt(20) + 1;
        throwScore = score;

        throwScoreBoxValue.setText(score + "");


    }//GEN-LAST:event_dartBoardPictureMouseClicked

    private void QuitToMainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitToMainMenuButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();   // closes the current Jframe window. 
        DartDashGUI gui = new DartDashGUI(); 
        gui.setVisible(true);
    }//GEN-LAST:event_QuitToMainMenuButtonActionPerformed
    /**
     * method to confirm score.
     *
     * @param evt
     */
    private void confirmNowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmNowButtonActionPerformed
        // TODO add your handling code here:
        if (throwRounds > 3 || throwRounds < 0 || confirmed > 2 || throwScore==0 ) {
            javax.swing.JOptionPane.showMessageDialog(null, "You cannot confim this round ", "Message", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return; 
        }
        setPanel2Color();////changes panel's color for fun. 
        throwRounds += 1;
        String s = throwRounds + "/3";
        throwBoxValue.setText(s);
        totalRoundScore += throwScore();
        throwScore = 0;
        throwScoreBoxValue.setText(throwScore+"");
        roundScoreBoxValue.setText(totalRoundScore + "");
        confirmed += 1;
        //confimredLast = true;

    }//GEN-LAST:event_confirmNowButtonActionPerformed
    /**
     * Method to undo score.
     *
     * @param evt
     */
    private void undoThrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoThrowButtonActionPerformed
        // TODO add your handling code here:
       
        
        if ((throwRounds == 0 && throwScore==0) || confirmed > 2 || throwScore== 0) {  ///this is debatable, since I think throws are going to be controllded by the game's manager's control flow. 
            javax.swing.JOptionPane.showMessageDialog(null, "You cannot undo a throw ", "Message", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            return;

            //throwRounds=0;
        }

        setPanel2Color();////changes panel's color for fun. 
        throwScore = 0;
        throwRounds -= 1;
        if (throwRounds < 0){
        throwRounds =0; 
        }
        throwScoreBoxValue.setText("0");

        String s = throwRounds + "/3";
        throwBoxValue.setText(s);
        roundScoreBoxValue.setText(totalRoundScore + "");
    }//GEN-LAST:event_undoThrowButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button QuitToMainMenuButton;
    private javax.swing.JPanel changingLightsBoardPanel;
    private java.awt.Button confirmNowButton;
    private javax.swing.JLabel dartBoardPicture;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label5;
    private javax.swing.JLabel playerNameBox;
    private java.awt.Label playerNameBoxValue;
    private javax.swing.JLabel playingTeamBox;
    private java.awt.Label playingTeamBoxValue;
    private java.awt.Label requiredScoreBox;
    private java.awt.Label roundBox;
    private javax.swing.JLabel roundScoreBox;
    private java.awt.Label roundScoreBoxValue;
    private java.awt.Label roundValueBox;
    private java.awt.Label teamABox;
    private java.awt.Label teamAName;
    private java.awt.Label teamBBox;
    private java.awt.Label teamBName;
    private java.awt.Label throwBox;
    private java.awt.Label throwBoxValue;
    private javax.swing.JLabel throwScoreBox;
    private java.awt.Label throwScoreBoxValue;
    private java.awt.Button undoThrowButton;
    // End of variables declaration//GEN-END:variables
}
