package com.cs321.gui;


import com.cs321.gui.DartDashGUI;
import com.cs321.gui.GUIState;
import com.cs321.gui.UpdateableJPanel;
import java.awt.LayoutManager;
import javax.swing.border.Border;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 Dart Gui. Empty file for dart display. 
 * @author guero
 */
public class Dart_2 extends UpdateableJPanel {
    int xDart= 0;
    int yDart=0; 
     int xMouse=0; 
     int yMouse=0; 
    private GUIState state;

    /**
     * Creates new form Dart
     */
    public Dart_2(GUIState state) {
        initComponents();
        this.state = state;
       //  state.contentPane.add("Dart_2", this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teamABox = new java.awt.Label();
        label2 = new java.awt.Label();
        teamAName = new java.awt.Label();
        teamBBox = new java.awt.Label();
        teamBName = new java.awt.Label();
        label5 = new java.awt.Label();
        startingScoreBoxValue = new java.awt.Label();
        roundBox = new java.awt.Label();
        roundValueBox = new java.awt.Label();
        throwBox = new java.awt.Label();
        throwBoxValue = new java.awt.Label();
        throwScoreBox = new javax.swing.JLabel();
        throwScoreBoxValue = new java.awt.Label();
        roundScoreBox = new javax.swing.JLabel();
        roundScoreBoxValue = new java.awt.Label();
        playingTeamBox = new javax.swing.JLabel();
        playingTeamBoxValue = new java.awt.Label();
        playerNameBox = new javax.swing.JLabel();
        playerNameBoxValue = new java.awt.Label();
        QuitToMainMenuButton = new java.awt.Button();
        undoThrowButton = new java.awt.Button();
        confirmNowButton = new java.awt.Button();
        changingLightsBoardPanel = new javax.swing.JPanel();
        dartBoardPicture = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1, 1));
        setPreferredSize(new java.awt.Dimension(640, 480));

        teamABox.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        teamABox.setText("Team ");

        label2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(102, 102, 102));
        label2.setText("Required Score: ");

        teamAName.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        teamAName.setText("A -34");

        teamBBox.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        teamBBox.setText("Team ");

        teamBName.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        teamBName.setText("B-57");

        label5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label5.setText("__________________________________________________________________________________________________________");

        startingScoreBoxValue.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        startingScoreBoxValue.setForeground(new java.awt.Color(102, 102, 102));
        startingScoreBoxValue.setText("0");

        roundBox.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        roundBox.setText("Round");

        roundValueBox.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        roundValueBox.setText("1");

        throwBox.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        throwBox.setText("Throw");

        throwBoxValue.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        throwBoxValue.setText("1/3");

        throwScoreBox.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        throwScoreBox.setForeground(new java.awt.Color(153, 0, 153));
        throwScoreBox.setText("Throw Score: ");

        throwScoreBoxValue.setText("label1");

        roundScoreBox.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        roundScoreBox.setForeground(new java.awt.Color(204, 0, 51));
        roundScoreBox.setText("Round Score: ");

        roundScoreBoxValue.setText("label1");

        playingTeamBox.setBackground(new java.awt.Color(204, 0, 51));
        playingTeamBox.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        playingTeamBox.setForeground(new java.awt.Color(204, 0, 51));
        playingTeamBox.setText("Playing Team: ");

        playingTeamBoxValue.setText("label2");

        playerNameBox.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        playerNameBox.setForeground(new java.awt.Color(204, 0, 51));
        playerNameBox.setText("Player's name: ");

        playerNameBoxValue.setText("label4");

        QuitToMainMenuButton.setBackground(new java.awt.Color(204, 255, 204));
        QuitToMainMenuButton.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        QuitToMainMenuButton.setLabel("Quit to Main Menu");
        QuitToMainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitToMainMenuButtonActionPerformed(evt);
            }
        });

        undoThrowButton.setBackground(new java.awt.Color(204, 255, 204));
        undoThrowButton.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        undoThrowButton.setLabel("Undo Throw");
        undoThrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoThrowButtonActionPerformed(evt);
            }
        });

        confirmNowButton.setBackground(new java.awt.Color(204, 255, 204));
        confirmNowButton.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        confirmNowButton.setLabel("Confirm Throw");
        confirmNowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmNowButtonActionPerformed(evt);
            }
        });

        dartBoardPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dartBoardPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dartBoard_1.png"))); // NOI18N
        dartBoardPicture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dartBoardPictureMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout changingLightsBoardPanelLayout = new javax.swing.GroupLayout(changingLightsBoardPanel);
        changingLightsBoardPanel.setLayout(changingLightsBoardPanelLayout);
        changingLightsBoardPanelLayout.setHorizontalGroup(
            changingLightsBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changingLightsBoardPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dartBoardPicture)
                .addGap(40, 40, 40))
        );
        changingLightsBoardPanelLayout.setVerticalGroup(
            changingLightsBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changingLightsBoardPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(dartBoardPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Dart/I can move ");
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(teamABox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teamAName, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(teamBBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teamBName, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playingTeamBox)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(roundBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roundValueBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(roundScoreBox)
                            .addComponent(playerNameBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(throwBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(throwBoxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(startingScoreBoxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(playerNameBoxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(roundScoreBoxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(playingTeamBoxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(74, 74, 74)
                                        .addComponent(changingLightsBoardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(throwScoreBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(throwScoreBoxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(115, 115, 115))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(undoThrowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(confirmNowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(QuitToMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(startingScoreBoxValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(teamABox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teamAName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teamBBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teamBName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(throwScoreBox)
                            .addComponent(throwScoreBoxValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundValueBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(throwBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(roundScoreBox)
                                    .addComponent(roundScoreBoxValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(playingTeamBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(playerNameBox))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(playingTeamBoxValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(playerNameBoxValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(changingLightsBoardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(throwBoxValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(QuitToMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(undoThrowButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmNowButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void QuitToMainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitToMainMenuButtonActionPerformed
        // TODO add your handling code here:
       
        // DartDashGUI gui = new DartDashGUI();
        //.setVisible(true);
        //gui.dispose();
        //this.dispose();
        //jPanel1.setVisible(false);
        //state.contentPaneCardLayout.show(state.contentPane, "MainMenuPanel");

        // state.contentPaneCardLayout.show(state.contentPane, "ViewGamemodesPanel");
       
         state.contentPaneCardLayout.show(state.contentPane, GUIState.PanelName.MainMenuPanel.toString());
    }//GEN-LAST:event_QuitToMainMenuButtonActionPerformed

    private void undoThrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoThrowButtonActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_undoThrowButtonActionPerformed

    private void confirmNowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmNowButtonActionPerformed
        // TODO add your handling code here:

      
    }//GEN-LAST:event_confirmNowButtonActionPerformed

    private void dartBoardPictureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dartBoardPictureMouseClicked
        // TODO add your handling code here:
        // System.out.println("throw round : "+ throwRounds);
        // jLabel2MouseDragged(evt);
//        Border border = dartBoardPicture.getBorder();
//       LayoutManager layout = dartBoardPicture.getLayout();
//       int x= layout.preferredLayoutSize(jLabel2).height;
//       int y=    layout.preferredLayoutSize(jLabel2).width;
int y=dartBoardPicture.getHorizontalAlignment();
int x = dartBoardPicture.getHorizontalAlignment();
//       
x = evt.getXOnScreen() - xMouse;
     y = evt.getYOnScreen() - yMouse;
//int newX = dartBoardPicture.getX()+x / 40;
//int newY = dartBoardPicture.getY() + y / 40;
int newX = x ;
int newY = y ;
    
    jLabel2.setLocation(newX, newY);
        
        
        
    }//GEN-LAST:event_dartBoardPictureMouseClicked

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
  int x = evt.getXOnScreen() - xMouse;
    int y = evt.getYOnScreen() - yMouse;
   int newX = jLabel2.getX() +x / 40;  
  int newY = jLabel2.getY() + y / 40;  
//int newX = dartBoardPicture.getX();
//int newY = dartBoardPicture.getY()+y ;
    
    jLabel2.setLocation(newX, newY);
    }//GEN-LAST:event_jLabel2MouseDragged
               
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

 
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
      xMouse = evt.getXOnScreen();
    yMouse = evt.getYOnScreen();
      
    }//GEN-LAST:event_jLabel2MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button QuitToMainMenuButton;
    private javax.swing.JPanel changingLightsBoardPanel;
    private java.awt.Button confirmNowButton;
    private javax.swing.JLabel dartBoardPicture;
    private javax.swing.JLabel jLabel2;
    private java.awt.Label label2;
    private java.awt.Label label5;
    private javax.swing.JLabel playerNameBox;
    private java.awt.Label playerNameBoxValue;
    private javax.swing.JLabel playingTeamBox;
    private java.awt.Label playingTeamBoxValue;
    private java.awt.Label roundBox;
    private javax.swing.JLabel roundScoreBox;
    private java.awt.Label roundScoreBoxValue;
    private java.awt.Label roundValueBox;
    private java.awt.Label startingScoreBoxValue;
    private java.awt.Label teamABox;
    private java.awt.Label teamAName;
    private java.awt.Label teamBBox;
    private java.awt.Label teamBName;
    private java.awt.Label throwBox;
    private java.awt.Label throwBoxValue;
    private javax.swing.JLabel throwScoreBox;
    private java.awt.Label throwScoreBoxValue;
    private java.awt.Button undoThrowButton;
    // End of variables declaration//GEN-END:variables
}
