/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cs321.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Hasna
 */
public class DartDashGUI extends javax.swing.JFrame {

    /**
     * Creates new form DartDashGUI
     */
    public DartDashGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        MainDisplayPanel = new javax.swing.JPanel();
        ViewGamemodesPanel = new javax.swing.JPanel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        ViewGamemodesTitlePanel = new javax.swing.JPanel();
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        ViewGamemodesTitleLabel = new javax.swing.JLabel();
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler27 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 40), new java.awt.Dimension(32767, 40));
        ViewGamemodesBodyPanel = new javax.swing.JPanel();
        ViewGamemodesContentPanel = new javax.swing.JPanel();
        ViewGamemodesExplorerPanel = new javax.swing.JPanel();
        ViewGamemodesExplorerHolderPanel = new javax.swing.JPanel();
        filler21 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        ViewGamemodesExplorerScrollPane = new javax.swing.JScrollPane();
        ViewGamemodesExplorerViewPanel = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        filler19 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler20 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        ViewGamemodesExplorerMenuPanel = new javax.swing.JPanel();
        ViewGamemodesCreateButton = new javax.swing.JButton();
        filler23 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        ViewGamemodesImportButton = new javax.swing.JButton();
        ViewGamemodesPropertiesPanel = new javax.swing.JPanel();
        ViewGamemodesPropertiesHolderPanel = new javax.swing.JPanel();
        filler22 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        ViewGamemodesPropertiesScrollPane = new javax.swing.JScrollPane();
        ViewGamemodesPropertiesViewPanel = new javax.swing.JPanel();
        ViewGamemodesIDLabel = new javax.swing.JLabel();
        ViewGamemodesCurrentIDLabel = new javax.swing.JLabel();
        ViewGamemodesNameLabel = new javax.swing.JLabel();
        ViewGamemodesCurrentNameLabel = new javax.swing.JLabel();
        ViewGamemodesDartsPerRoundLabel = new javax.swing.JLabel();
        ViewGamemodesCurrentDartsPerRoundLabel = new javax.swing.JLabel();
        ViewGamemodesMaximumRoundsLabel = new javax.swing.JLabel();
        ViewGamemodesCurrentMaximumRounds = new javax.swing.JLabel();
        ViewGamemodesStartingScoreLabel = new javax.swing.JLabel();
        ViewGamemodesCurrentStartingScoreLabel = new javax.swing.JLabel();
        ViewGamemodesOffboardPenaltyLabel = new javax.swing.JLabel();
        ViewGamemodesCurrentOffboardPenaltyLabel = new javax.swing.JLabel();
        ViewGamemodesScoreListLabel = new javax.swing.JLabel();
        ViewGamemodesCurrentScoreListLabel = new javax.swing.JLabel();
        ViewGamemodesMultipliersLabel = new javax.swing.JLabel();
        ViewGamemodesCurrentMultipliersLabel = new javax.swing.JLabel();
        ViewGamemodesExactZeroWinLabel = new javax.swing.JLabel();
        ViewGamemodesCurrentExactZeroWinLabel = new javax.swing.JLabel();
        ViewGamemodesSubtractPointsLabel = new javax.swing.JLabel();
        ViewGamemodesCurrentSubtractPointsLabel = new javax.swing.JLabel();
        filler29 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler24 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        ViewGamemodesPropertiesMenuPanel = new javax.swing.JPanel();
        ViewGamemodesEditButton = new javax.swing.JButton();
        filler25 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        ViewGamemodesExportButton = new javax.swing.JButton();
        filler26 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        ViewGamemodesDeleteButton = new javax.swing.JButton();
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler28 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 40), new java.awt.Dimension(32767, 40));
        ViewGamemodesMenuPanel = new javax.swing.JPanel();
        filler18 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        ViewGamemodesBackToMainMenuButton = new javax.swing.JButton();
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        MainMenuPanel = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        MainMenuTitlePanel = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        MainMenuTitleLabel = new javax.swing.JLabel();
        MainMenuTitleImageLabel = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        MainMenuBodyPanel = new javax.swing.JPanel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        MainMenuButtonsPanel = new javax.swing.JPanel();
        MainMenuPlayGameButton = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        MainMenuViewPlayersButton = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        MainMenuViewGamemodesButton = new javax.swing.JButton();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        MainMenuQuitButton = new javax.swing.JButton();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        MainDisplayPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        MainDisplayPanel.setLayout(new java.awt.CardLayout());

        ViewGamemodesPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        ViewGamemodesPanel.setLayout(new javax.swing.BoxLayout(ViewGamemodesPanel, javax.swing.BoxLayout.Y_AXIS));
        ViewGamemodesPanel.add(filler11);

        ViewGamemodesTitlePanel.setPreferredSize(new java.awt.Dimension(800, 100));
        ViewGamemodesTitlePanel.setLayout(new javax.swing.BoxLayout(ViewGamemodesTitlePanel, javax.swing.BoxLayout.X_AXIS));
        ViewGamemodesTitlePanel.add(filler14);

        ViewGamemodesTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        ViewGamemodesTitleLabel.setText("View Gamemodes");
        ViewGamemodesTitlePanel.add(ViewGamemodesTitleLabel);
        ViewGamemodesTitlePanel.add(filler15);

        ViewGamemodesPanel.add(ViewGamemodesTitlePanel);
        ViewGamemodesPanel.add(filler12);
        ViewGamemodesPanel.add(filler27);

        ViewGamemodesBodyPanel.setLayout(new javax.swing.BoxLayout(ViewGamemodesBodyPanel, javax.swing.BoxLayout.Y_AXIS));

        ViewGamemodesContentPanel.setMinimumSize(new java.awt.Dimension(200, 68));
        ViewGamemodesContentPanel.setPreferredSize(new java.awt.Dimension(200, 457));
        ViewGamemodesContentPanel.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        ViewGamemodesExplorerPanel.setPreferredSize(new java.awt.Dimension(400, 300));
        ViewGamemodesExplorerPanel.setLayout(new javax.swing.BoxLayout(ViewGamemodesExplorerPanel, javax.swing.BoxLayout.Y_AXIS));

        ViewGamemodesExplorerHolderPanel.setLayout(new javax.swing.BoxLayout(ViewGamemodesExplorerHolderPanel, javax.swing.BoxLayout.X_AXIS));
        ViewGamemodesExplorerHolderPanel.add(filler21);

        ViewGamemodesExplorerScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        ViewGamemodesExplorerViewPanel.setMinimumSize(new java.awt.Dimension(200, 400));
        ViewGamemodesExplorerViewPanel.setPreferredSize(new java.awt.Dimension(200, 400));
        ViewGamemodesExplorerViewPanel.setLayout(new java.awt.GridLayout(0, 1));

        jToggleButton1.setText("jToggleButton1");
        ViewGamemodesExplorerViewPanel.add(jToggleButton1);

        jToggleButton2.setText("jToggleButton1");
        ViewGamemodesExplorerViewPanel.add(jToggleButton2);

        jToggleButton3.setText("jToggleButton1");
        ViewGamemodesExplorerViewPanel.add(jToggleButton3);

        jToggleButton4.setText("jToggleButton1");
        ViewGamemodesExplorerViewPanel.add(jToggleButton4);

        jToggleButton5.setText("jToggleButton1");
        ViewGamemodesExplorerViewPanel.add(jToggleButton5);

        jToggleButton6.setText("jToggleButton1");
        ViewGamemodesExplorerViewPanel.add(jToggleButton6);

        jToggleButton7.setText("jToggleButton1");
        ViewGamemodesExplorerViewPanel.add(jToggleButton7);

        jToggleButton8.setText("jToggleButton1");
        ViewGamemodesExplorerViewPanel.add(jToggleButton8);

        jToggleButton9.setText("jToggleButton1");
        ViewGamemodesExplorerViewPanel.add(jToggleButton9);

        jToggleButton10.setText("jToggleButton1");
        ViewGamemodesExplorerViewPanel.add(jToggleButton10);

        jToggleButton11.setText("jToggleButton1");
        ViewGamemodesExplorerViewPanel.add(jToggleButton11);

        jToggleButton12.setText("jToggleButton1");
        ViewGamemodesExplorerViewPanel.add(jToggleButton12);

        jToggleButton13.setText("jToggleButton1");
        ViewGamemodesExplorerViewPanel.add(jToggleButton13);

        jToggleButton14.setText("jToggleButton1");
        ViewGamemodesExplorerViewPanel.add(jToggleButton14);

        jToggleButton15.setText("jToggleButton1");
        ViewGamemodesExplorerViewPanel.add(jToggleButton15);

        jToggleButton16.setText("jToggleButton1");
        ViewGamemodesExplorerViewPanel.add(jToggleButton16);

        jToggleButton17.setText("jToggleButton1");
        ViewGamemodesExplorerViewPanel.add(jToggleButton17);

        jToggleButton18.setText("jToggleButton1");
        ViewGamemodesExplorerViewPanel.add(jToggleButton18);

        ViewGamemodesExplorerScrollPane.setViewportView(ViewGamemodesExplorerViewPanel);

        ViewGamemodesExplorerHolderPanel.add(ViewGamemodesExplorerScrollPane);
        ViewGamemodesExplorerHolderPanel.add(filler19);

        ViewGamemodesExplorerPanel.add(ViewGamemodesExplorerHolderPanel);
        ViewGamemodesExplorerPanel.add(filler20);

        ViewGamemodesExplorerMenuPanel.setLayout(new javax.swing.BoxLayout(ViewGamemodesExplorerMenuPanel, javax.swing.BoxLayout.X_AXIS));

        ViewGamemodesCreateButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ViewGamemodesCreateButton.setText("Create New");
        ViewGamemodesExplorerMenuPanel.add(ViewGamemodesCreateButton);
        ViewGamemodesExplorerMenuPanel.add(filler23);

        ViewGamemodesImportButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ViewGamemodesImportButton.setText("Import New");
        ViewGamemodesExplorerMenuPanel.add(ViewGamemodesImportButton);

        ViewGamemodesExplorerPanel.add(ViewGamemodesExplorerMenuPanel);

        ViewGamemodesContentPanel.add(ViewGamemodesExplorerPanel);

        ViewGamemodesPropertiesPanel.setPreferredSize(new java.awt.Dimension(400, 300));
        ViewGamemodesPropertiesPanel.setLayout(new javax.swing.BoxLayout(ViewGamemodesPropertiesPanel, javax.swing.BoxLayout.Y_AXIS));

        ViewGamemodesPropertiesHolderPanel.setLayout(new javax.swing.BoxLayout(ViewGamemodesPropertiesHolderPanel, javax.swing.BoxLayout.X_AXIS));
        ViewGamemodesPropertiesHolderPanel.add(filler22);

        ViewGamemodesPropertiesScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        ViewGamemodesPropertiesViewPanel.setMinimumSize(new java.awt.Dimension(200, 300));
        ViewGamemodesPropertiesViewPanel.setPreferredSize(new java.awt.Dimension(200, 300));
        ViewGamemodesPropertiesViewPanel.setLayout(new java.awt.GridBagLayout());

        ViewGamemodesIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewGamemodesIDLabel.setText("ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        ViewGamemodesPropertiesViewPanel.add(ViewGamemodesIDLabel, gridBagConstraints);

        ViewGamemodesCurrentIDLabel.setText("----");
        ViewGamemodesPropertiesViewPanel.add(ViewGamemodesCurrentIDLabel, new java.awt.GridBagConstraints());

        ViewGamemodesNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewGamemodesNameLabel.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        ViewGamemodesPropertiesViewPanel.add(ViewGamemodesNameLabel, gridBagConstraints);

        ViewGamemodesCurrentNameLabel.setText("----");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        ViewGamemodesPropertiesViewPanel.add(ViewGamemodesCurrentNameLabel, gridBagConstraints);

        ViewGamemodesDartsPerRoundLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewGamemodesDartsPerRoundLabel.setText("Darts Per Round:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        ViewGamemodesPropertiesViewPanel.add(ViewGamemodesDartsPerRoundLabel, gridBagConstraints);

        ViewGamemodesCurrentDartsPerRoundLabel.setText("----");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        ViewGamemodesPropertiesViewPanel.add(ViewGamemodesCurrentDartsPerRoundLabel, gridBagConstraints);

        ViewGamemodesMaximumRoundsLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewGamemodesMaximumRoundsLabel.setText("Maximum Rounds:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        ViewGamemodesPropertiesViewPanel.add(ViewGamemodesMaximumRoundsLabel, gridBagConstraints);

        ViewGamemodesCurrentMaximumRounds.setText("----");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        ViewGamemodesPropertiesViewPanel.add(ViewGamemodesCurrentMaximumRounds, gridBagConstraints);

        ViewGamemodesStartingScoreLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewGamemodesStartingScoreLabel.setText("Starting Score:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        ViewGamemodesPropertiesViewPanel.add(ViewGamemodesStartingScoreLabel, gridBagConstraints);

        ViewGamemodesCurrentStartingScoreLabel.setText("----");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        ViewGamemodesPropertiesViewPanel.add(ViewGamemodesCurrentStartingScoreLabel, gridBagConstraints);

        ViewGamemodesOffboardPenaltyLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewGamemodesOffboardPenaltyLabel.setText("Offboard Penalty:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        ViewGamemodesPropertiesViewPanel.add(ViewGamemodesOffboardPenaltyLabel, gridBagConstraints);

        ViewGamemodesCurrentOffboardPenaltyLabel.setText("----");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        ViewGamemodesPropertiesViewPanel.add(ViewGamemodesCurrentOffboardPenaltyLabel, gridBagConstraints);

        ViewGamemodesScoreListLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewGamemodesScoreListLabel.setText("Score List:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        ViewGamemodesPropertiesViewPanel.add(ViewGamemodesScoreListLabel, gridBagConstraints);

        ViewGamemodesCurrentScoreListLabel.setText("----");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        ViewGamemodesPropertiesViewPanel.add(ViewGamemodesCurrentScoreListLabel, gridBagConstraints);

        ViewGamemodesMultipliersLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewGamemodesMultipliersLabel.setText("Multipliers:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        ViewGamemodesPropertiesViewPanel.add(ViewGamemodesMultipliersLabel, gridBagConstraints);

        ViewGamemodesCurrentMultipliersLabel.setText("----");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        ViewGamemodesPropertiesViewPanel.add(ViewGamemodesCurrentMultipliersLabel, gridBagConstraints);

        ViewGamemodesExactZeroWinLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewGamemodesExactZeroWinLabel.setText("Exact Zero Win:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        ViewGamemodesPropertiesViewPanel.add(ViewGamemodesExactZeroWinLabel, gridBagConstraints);

        ViewGamemodesCurrentExactZeroWinLabel.setText("----");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        ViewGamemodesPropertiesViewPanel.add(ViewGamemodesCurrentExactZeroWinLabel, gridBagConstraints);

        ViewGamemodesSubtractPointsLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewGamemodesSubtractPointsLabel.setText("Subtract Points:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        ViewGamemodesPropertiesViewPanel.add(ViewGamemodesSubtractPointsLabel, gridBagConstraints);

        ViewGamemodesCurrentSubtractPointsLabel.setText("----");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        ViewGamemodesPropertiesViewPanel.add(ViewGamemodesCurrentSubtractPointsLabel, gridBagConstraints);

        ViewGamemodesPropertiesScrollPane.setViewportView(ViewGamemodesPropertiesViewPanel);

        ViewGamemodesPropertiesHolderPanel.add(ViewGamemodesPropertiesScrollPane);
        ViewGamemodesPropertiesHolderPanel.add(filler29);

        ViewGamemodesPropertiesPanel.add(ViewGamemodesPropertiesHolderPanel);
        ViewGamemodesPropertiesPanel.add(filler24);

        ViewGamemodesPropertiesMenuPanel.setLayout(new javax.swing.BoxLayout(ViewGamemodesPropertiesMenuPanel, javax.swing.BoxLayout.X_AXIS));

        ViewGamemodesEditButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ViewGamemodesEditButton.setText("Edit");
        ViewGamemodesEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewGamemodesEditButtonActionPerformed(evt);
            }
        });
        ViewGamemodesPropertiesMenuPanel.add(ViewGamemodesEditButton);
        ViewGamemodesPropertiesMenuPanel.add(filler25);

        ViewGamemodesExportButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ViewGamemodesExportButton.setText("Export");
        ViewGamemodesPropertiesMenuPanel.add(ViewGamemodesExportButton);
        ViewGamemodesPropertiesMenuPanel.add(filler26);

        ViewGamemodesDeleteButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ViewGamemodesDeleteButton.setText("Delete");
        ViewGamemodesPropertiesMenuPanel.add(ViewGamemodesDeleteButton);

        ViewGamemodesPropertiesPanel.add(ViewGamemodesPropertiesMenuPanel);

        ViewGamemodesContentPanel.add(ViewGamemodesPropertiesPanel);

        ViewGamemodesBodyPanel.add(ViewGamemodesContentPanel);
        ViewGamemodesBodyPanel.add(filler16);
        ViewGamemodesBodyPanel.add(filler28);

        ViewGamemodesMenuPanel.setPreferredSize(new java.awt.Dimension(400, 100));
        ViewGamemodesMenuPanel.setLayout(new javax.swing.BoxLayout(ViewGamemodesMenuPanel, javax.swing.BoxLayout.X_AXIS));
        ViewGamemodesMenuPanel.add(filler18);

        ViewGamemodesBackToMainMenuButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ViewGamemodesBackToMainMenuButton.setText("Back to Main Menu");
        ViewGamemodesMenuPanel.add(ViewGamemodesBackToMainMenuButton);
        ViewGamemodesMenuPanel.add(filler17);

        ViewGamemodesBodyPanel.add(ViewGamemodesMenuPanel);

        ViewGamemodesPanel.add(ViewGamemodesBodyPanel);
        ViewGamemodesPanel.add(filler13);

        MainDisplayPanel.add(ViewGamemodesPanel, "card3");

        MainMenuPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        MainMenuPanel.setLayout(new javax.swing.BoxLayout(MainMenuPanel, javax.swing.BoxLayout.Y_AXIS));
        MainMenuPanel.add(filler4);

        MainMenuTitlePanel.setLayout(new javax.swing.BoxLayout(MainMenuTitlePanel, javax.swing.BoxLayout.X_AXIS));
        MainMenuTitlePanel.add(filler2);

        MainMenuTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        MainMenuTitleLabel.setText("DartDash ");
        MainMenuTitlePanel.add(MainMenuTitleLabel);

        MainMenuTitleImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dartboard.png"))); // NOI18N
        MainMenuTitlePanel.add(MainMenuTitleImageLabel);
        MainMenuTitlePanel.add(filler3);

        MainMenuPanel.add(MainMenuTitlePanel);
        MainMenuPanel.add(filler1);

        MainMenuBodyPanel.setLayout(new javax.swing.BoxLayout(MainMenuBodyPanel, javax.swing.BoxLayout.X_AXIS));
        MainMenuBodyPanel.add(filler9);

        MainMenuButtonsPanel.setLayout(new javax.swing.BoxLayout(MainMenuButtonsPanel, javax.swing.BoxLayout.Y_AXIS));

        MainMenuPlayGameButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MainMenuPlayGameButton.setText("Play Game");
        MainMenuPlayGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuPlayGameButtonActionPerformed(evt);
            }
        });
        MainMenuButtonsPanel.add(MainMenuPlayGameButton);
        MainMenuButtonsPanel.add(filler6);

        MainMenuViewPlayersButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MainMenuViewPlayersButton.setText("View Players");
        MainMenuViewPlayersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuViewPlayersButtonActionPerformed(evt);
            }
        });
        MainMenuButtonsPanel.add(MainMenuViewPlayersButton);
        MainMenuButtonsPanel.add(filler7);

        MainMenuViewGamemodesButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MainMenuViewGamemodesButton.setText("View Gamemodes");
        MainMenuViewGamemodesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuViewGamemodesButtonActionPerformed(evt);
            }
        });
        MainMenuButtonsPanel.add(MainMenuViewGamemodesButton);
        MainMenuButtonsPanel.add(filler8);

        MainMenuQuitButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MainMenuQuitButton.setText("Quit");
        MainMenuQuitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuQuitButtonActionPerformed(evt);
            }
        });
        MainMenuButtonsPanel.add(MainMenuQuitButton);

        MainMenuBodyPanel.add(MainMenuButtonsPanel);
        MainMenuBodyPanel.add(filler10);

        MainMenuPanel.add(MainMenuBodyPanel);
        MainMenuPanel.add(filler5);

        MainDisplayPanel.add(MainMenuPanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1201, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainMenuPlayGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuPlayGameButtonActionPerformed
        // TODO add your handling code here:
        
       
   
      // this is supposed to open the PLAY frame (dart class) but it is not opening for some reason. 
    
            dart dartFrame = new dart();   
           // this.dispose();
        
            dartFrame.setVisible(true);   
        
 
    }//GEN-LAST:event_MainMenuPlayGameButtonActionPerformed

    private void MainMenuQuitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuQuitButtonActionPerformed
        // TODO add your handling code here:
        //exits the game. 
        System.exit(0);
    }//GEN-LAST:event_MainMenuQuitButtonActionPerformed

    private void MainMenuViewGamemodesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuViewGamemodesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MainMenuViewGamemodesButtonActionPerformed

    private void MainMenuViewPlayersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuViewPlayersButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MainMenuViewPlayersButtonActionPerformed

    private void ViewGamemodesEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewGamemodesEditButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewGamemodesEditButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//     public static void main(String args[]) {
//         /* Set the Nimbus look and feel */
//         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//         /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//          * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//          */
//         try {
// //            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
// //                if ("Nimbus".equals(info.getName())) {
// //                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
// //                    break;
// //                }
// //            }
            
//             javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            
//         } catch (ClassNotFoundException ex) {
//             java.util.logging.Logger.getLogger(DartDashGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         } catch (InstantiationException ex) {
//             java.util.logging.Logger.getLogger(DartDashGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         } catch (IllegalAccessException ex) {
//             java.util.logging.Logger.getLogger(DartDashGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//             java.util.logging.Logger.getLogger(DartDashGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         }
//         //</editor-fold>

//         /* Create and display the form */
//         java.awt.EventQueue.invokeLater(new Runnable() {
//             public void run() {
//                 new DartDashGUI().setVisible(true);
//             }
//         });
//     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainDisplayPanel;
    private javax.swing.JPanel MainMenuBodyPanel;
    private javax.swing.JPanel MainMenuButtonsPanel;
    private javax.swing.JPanel MainMenuPanel;
    private javax.swing.JButton MainMenuPlayGameButton;
    private javax.swing.JButton MainMenuQuitButton;
    private javax.swing.JLabel MainMenuTitleImageLabel;
    private javax.swing.JLabel MainMenuTitleLabel;
    private javax.swing.JPanel MainMenuTitlePanel;
    private javax.swing.JButton MainMenuViewGamemodesButton;
    private javax.swing.JButton MainMenuViewPlayersButton;
    private javax.swing.JButton ViewGamemodesBackToMainMenuButton;
    private javax.swing.JPanel ViewGamemodesBodyPanel;
    private javax.swing.JPanel ViewGamemodesContentPanel;
    private javax.swing.JButton ViewGamemodesCreateButton;
    private javax.swing.JLabel ViewGamemodesCurrentDartsPerRoundLabel;
    private javax.swing.JLabel ViewGamemodesCurrentExactZeroWinLabel;
    private javax.swing.JLabel ViewGamemodesCurrentIDLabel;
    private javax.swing.JLabel ViewGamemodesCurrentMaximumRounds;
    private javax.swing.JLabel ViewGamemodesCurrentMultipliersLabel;
    private javax.swing.JLabel ViewGamemodesCurrentNameLabel;
    private javax.swing.JLabel ViewGamemodesCurrentOffboardPenaltyLabel;
    private javax.swing.JLabel ViewGamemodesCurrentScoreListLabel;
    private javax.swing.JLabel ViewGamemodesCurrentStartingScoreLabel;
    private javax.swing.JLabel ViewGamemodesCurrentSubtractPointsLabel;
    private javax.swing.JLabel ViewGamemodesDartsPerRoundLabel;
    private javax.swing.JButton ViewGamemodesDeleteButton;
    private javax.swing.JButton ViewGamemodesEditButton;
    private javax.swing.JLabel ViewGamemodesExactZeroWinLabel;
    private javax.swing.JPanel ViewGamemodesExplorerHolderPanel;
    private javax.swing.JPanel ViewGamemodesExplorerMenuPanel;
    private javax.swing.JPanel ViewGamemodesExplorerPanel;
    private javax.swing.JScrollPane ViewGamemodesExplorerScrollPane;
    private javax.swing.JPanel ViewGamemodesExplorerViewPanel;
    private javax.swing.JButton ViewGamemodesExportButton;
    private javax.swing.JLabel ViewGamemodesIDLabel;
    private javax.swing.JButton ViewGamemodesImportButton;
    private javax.swing.JLabel ViewGamemodesMaximumRoundsLabel;
    private javax.swing.JPanel ViewGamemodesMenuPanel;
    private javax.swing.JLabel ViewGamemodesMultipliersLabel;
    private javax.swing.JLabel ViewGamemodesNameLabel;
    private javax.swing.JLabel ViewGamemodesOffboardPenaltyLabel;
    private javax.swing.JPanel ViewGamemodesPanel;
    private javax.swing.JPanel ViewGamemodesPropertiesHolderPanel;
    private javax.swing.JPanel ViewGamemodesPropertiesMenuPanel;
    private javax.swing.JPanel ViewGamemodesPropertiesPanel;
    private javax.swing.JScrollPane ViewGamemodesPropertiesScrollPane;
    private javax.swing.JPanel ViewGamemodesPropertiesViewPanel;
    private javax.swing.JLabel ViewGamemodesScoreListLabel;
    private javax.swing.JLabel ViewGamemodesStartingScoreLabel;
    private javax.swing.JLabel ViewGamemodesSubtractPointsLabel;
    private javax.swing.JLabel ViewGamemodesTitleLabel;
    private javax.swing.JPanel ViewGamemodesTitlePanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler17;
    private javax.swing.Box.Filler filler18;
    private javax.swing.Box.Filler filler19;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler20;
    private javax.swing.Box.Filler filler21;
    private javax.swing.Box.Filler filler22;
    private javax.swing.Box.Filler filler23;
    private javax.swing.Box.Filler filler24;
    private javax.swing.Box.Filler filler25;
    private javax.swing.Box.Filler filler26;
    private javax.swing.Box.Filler filler27;
    private javax.swing.Box.Filler filler28;
    private javax.swing.Box.Filler filler29;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
